### ISSUE TITLE
Dimension errors

### ISSUE THREAD

**Issue by anamce** [elnino9ykl/OmniSupervised-ConvNet#1]
Hi , I just picked ERFPSPNEt to train on my custom dataset and I am getting this error 
RuntimeError: Given input size: (128x32x64). Calculated output size: (128x0x0). Output size is too small
Could you please help me ?

**Comment by elnino9ykl** [comment]
The input size is a bit small, you could try first enlarging the input size and check whether it works.

**Comment by anamce** [comment]
Hi I changed input resolution from (512,512) to (512,1024) still it doesn’t work .

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by anamce** [comment]
I also run this github repo over the cityscapes but it throws assersion errors m using 1 GPU.
Could you please guide me on this :)

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by elnino9ykl** [comment]
Hi, you could try printing the size of the tensors in the network for debugging. Then, you will have a better understanding of what happens there.

**Comment by anamce** [comment]
Alright! I might get back to you 👍

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
